### ISSUE TITLE
DataPrepare

### ISSUE THREAD

**Issue by AmingWu** [BCV-Uniandes/DMS#22]
Traceback (most recent call last):
  File "refer.py", line 39, in <module>
    from external import mask
  File "/home/wam/refer-master/external/mask.py", line 3, in <module>
    import external._mask as _mask
ImportError: No module named _mask
Could you give me some advice to solve the error?

**Comment by andfoy** [comment]
Which version of Referit did you downloaded?

**Comment by AmingWu** [comment]
I use the link of https://github.com/lichengunc/refer to download the Referit

**Comment by andfoy** [comment]
Could you please install our version of referit and try again? https://github.com/andfoy/refer

**Comment by AmingWu** [comment]
How much GPU does this work usually require?

**Comment by andfoy** [comment]
> How much GPU does this work usually require?

It requires about 12Gb to train the whole model.

**Comment by andfoy** [comment]
@AmingWu I hope that your issue was resolved. I'm closing this one.

**Comment by AmingWu** [comment]
Sorry, I cannot obtain your data. There is an error.
ModuleNotFoundError: No module named 'referit.external._mask'

**Comment by andfoy** [comment]
@AmingWu Could you please try to follow the instructions posted on the project [README](https://github.com/BCV-Uniandes/DMS/blob/master/README.md)?

**Comment by andfoy** [comment]
@AmingWu Any followup on this one?
