### ISSUE TITLE
Question of REFER

### ISSUE THREAD

**Issue by WangLanxiao** [BCV-Uniandes/DMS#24]
I have these words in readme in order to install refer
    sudo pip install git+https://github.com/andfoy/refer.git
    sudo pip install -U git+https://github.com/taolei87/sru.git@43c85ed --no-deps
But I still meet:
Traceback (most recent call last):
  File "/home/lanxiao/DMS-master/dmn_pytorch/train.py", line 23, in <module>
    from dmn_pytorch.models import DMN
  File "/home/lanxiao/DMS-master/dmn_pytorch/__init__.py", line 12, in <module>
    from .referit_loader import ReferDataset
  File "/home/lanxiao/DMS-master/dmn_pytorch/referit_loader.py", line 21, in <module>
    from referit import REFER
ImportError: cannot import name 'REFER'

**Comment by andfoy** [comment]
Hi, thanks for your question. Which version of Python are you using?

**Comment by WangLanxiao** [comment]
thanks for your reply!
python3.6

**Comment by andfoy** [comment]
What happens if you try to import the conflicting package on a Python interpreter instance? Are you executing the code with your system's Python?

PD: Have you tried to isolate your dependencies on a virtualenv/conda? If not, could you try to see if the error is reproduced?

**Comment by WangLanxiao** [comment]
I clone https://github.com/andfoy/refer.git  by myself 
and then set :
    sudo  pip install -U .
now this problem has been solved.
But I meet " No such file or directory: 'data/unc/corpus.pth" I think i need to  check my datafolder.
Thanks for your kind explanation.I learn a lot from you project!

**Comment by andfoy** [comment]
>  But I meet " No such file or directory: 'data/unc/corpus.pth" I think i need to check my datafolder.

To solve this one, you just need to delete the ``data`` folder that was generated.

**Comment by andfoy** [comment]
Thanks for your feedback on our work!
