### ISSUE TITLE
Why net.train() in evaluate function?

### ISSUE THREAD

**Issue by RyanHTR** [BCV-Uniandes/DMS#30]
Hi, i notice that the network is set to train mode in evaluate function. Is that a special setting? Does this line affect the results of evaluation?

https://github.com/BCV-Uniandes/DMS/blob/9fa3a3a2ef5980dd17e21b73234a4cd0b3d00e16/dmn_pytorch/train.py#L342

**Comment by andfoy** [comment]
Hi, we evaluate on train mode due to the unstability of BN blocks of the backbone network, i.e., DPN-92. As we train with batch size = 1, the model is unable to capture proper statistics per "batch" (Instance, actually)

**Comment by andfoy** [comment]
Due to a lack of responses, I'm closing this one
