### ISSUE TITLE
How to visualize the output?

### ISSUE THREAD

**Issue by skynbe** [BCV-Uniandes/DMS#31]
I reproduced your model and got the same result on UNC dataset / val split. However, when I try to visualize the output, the segmentation mask is messy. Could you let me know how to visualize the output like as this figure?

![image](https://user-images.githubusercontent.com/3962617/63644558-91852580-c6a0-11e9-9ee1-7ac415ff1eee.png)

**Comment by andfoy** [comment]
Hi @skynbe, thanks for contacting us and sorry for the late reply. Which command are you running to visualize DMN outputs?

**Comment by andfoy** [comment]
Please refer to #32
