### ISSUE TITLE
Pretrained weights link seems to be down

### ISSUE THREAD

**Issue by tgieruc** [BCV-Uniandes/DMS#37]
The download link to all pretrained weights seem to be down, for example [this one](http://marr.uniandes.edu.co/weights/dmn/highres/dmn_referit_weights.pth).

Would it be possible to upload the pretrained weights on another platform?

**Comment by andfoy** [comment]
Hi @tgieruc, unfortunately I left the organization many years ago and I'm not sure what happened with the servers and their data. However, when the model was developed it only worked in a very very old version of PyTorch (0.2.x) and most probably those weights wouldn't work nowadays. The only alternative would be to retrain everything from scratch

**Comment by tgieruc** [comment]
Okay, thank you for your response, I will look into doing an implementation with a more modern version of PyTorch 👍 
How much time did you need to train everything from scratch, approximately ?

**Comment by andfoy** [comment]
It took about 5 days, due to the single batch training restriction
